/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import InterfacesVentana.IConsultas;
import Controlador.Controlador;
import InterfazCommon.IPartida;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sebastian
 */
public final class JPConsultas extends javax.swing.JPanel implements IConsultas {

    /**
     * Creates new form JPLogin
     */
    public JPConsultas() {

        iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGanancias = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        lblGanancias = new javax.swing.JLabel();
        btnHistoricoPartidas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaHistorial = new javax.swing.JTextArea();

        btnGanancias.setText("Ver Ganancias");
        btnGanancias.setActionCommand("VerGanancias");
        btnGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGananciasActionPerformed(evt);
            }
        });

        lblMensaje.setForeground(new java.awt.Color(204, 0, 0));

        btnHistoricoPartidas.setText("Historico Partidas");
        btnHistoricoPartidas.setActionCommand("HistoricoPartidas");

        jtaHistorial.setColumns(20);
        jtaHistorial.setRows(5);
        jScrollPane1.setViewportView(jtaHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHistoricoPartidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGanancias, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGanancias)
                    .addComponent(lblGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHistoricoPartidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGananciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGananciasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGanancias;
    private javax.swing.JButton btnHistoricoPartidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaHistorial;
    private javax.swing.JLabel lblGanancias;
    private javax.swing.JLabel lblMensaje;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlador(Controlador c) {
        this.btnGanancias.addActionListener(c);
        this.btnHistoricoPartidas.addActionListener(c);
    }

    @Override
    public void iniciarComponentes() {

        this.setVisible(true);
        this.setSize(500, 500);
        initComponents();
    }

    @Override
    public void setLblMensaje(String mensaje) {
        this.lblMensaje.setText(mensaje);
    }

    @Override
    public void setGanancias(float ganancias) {
        this.lblGanancias.setText("Ganancias Totales: $ " + ganancias);
    }

    @Override
    public void setHistoricoPartidas(ArrayList<String> listaPartidas) {
        for(int i = 0; i < listaPartidas.size(); i++){
            System.out.println(listaPartidas.get(i));
            this.jtaHistorial.append(listaPartidas.get(i) + "\r\n");
        }
    }

    @Override
    public void limpiarCampos() {
        this.jtaHistorial.setText("");
    }

}
